### ISSUE TITLE
Error in running Matlab Code 

### ISSUE THREAD

**Issue by azwaw-y** [M-R-FARHADI/ComfTool#1]
Hello,

I have been trying to run  the Matlab code you posted , but getting the following error:

Starting parallel pool (parpool) using the 'local' profile ...
Connected to the parallel pool (number of workers: 4).
CALCULATING ...
Analyzing and transferring files to the workers ...done.
Error using Validation (line 15)
The source code (F:\MATLAB\ThermalComfort\ISO 7730\PMV-PPD\Validation.m) for the parfor-loop that is trying to execute on the worker could
not be found.

Caused by:
    Undefined function 'FangerD' for input arguments of type 'double'.
    Error using remoteParallelFunction (line 94)
    Worker unable to find file.
        Undefined function 'FangerD' for input arguments of type 'double'.
 
IdleTimeout has been reached.
Parallel pool using the 'local' profile is shutting down.

----------------

Could you please help me in solving this error?

Thank you!

**Comment by M-R-FARHADI** [comment]
Hello,
Thanks for replying
Please copy all functions in function folder to main folder or changing your directory in function folder or redownload and test it's working well.

**Comment by M-R-FARHADI** [comment]
your problem is matlab don't know where is important functions. :)
